name: chemistry
description: State manager that separates pure state and derived state. It aims to be easy to use.
version: 1.0.0
repository: https://github.com/simonwahll/chemistry

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
